#include "HistoSpecialisers.h"
/*template class THistoGraph<TH1C>;
template class THistoGraph<TH1S>;
template class THistoGraph<TH1I>;
template class THistoGraph<TH1F>;
template class THistoGraph<TH1D>;
template class THistoGraph<TH2C>;
template class THistoGraph<TH2S>;
template class THistoGraph<TH2I>;
template class THistoGraph<TH2F>;
template class THistoGraph<TH2D>;
template class THistoGraph<TH3C>;
template class THistoGraph<TH3S>;
template class THistoGraph<TH3I>;
template class THistoGraph<TH3F>;
template class THistoGraph<TH3D>; 
template class THistoGraph<TProfile>;
template class THistoGraph<TProfile2D>;
template class THistoGraph<TProfile3D>;*/
